update=lun 01 sep 2014 16:39:42 CST
version=1
last_client=pcbnew
[general]
version=1
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=special
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=Three-phase_bridge
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=Three-phase bridge.net
UseCmpFile=1
PadDrill="    0,127000"
PadDrillOvalY="    0,127000"
PadSizeH="    2,463800"
PadSizeV="    2,463800"
PcbTextSizeV="    1,500000"
PcbTextSizeH="    1,500000"
PcbTextThickness="    0,300000"
ModuleTextSizeV="    1,000000"
ModuleTextSizeH="    1,000000"
ModuleTextSizeThickness="    0,150000"
SolderMaskClearance="    0,000000"
SolderMaskMinWidth="    0,000000"
DrawSegmentWidth="    0,200000"
BoardOutlineThickness="    0,100000"
ModuleOutlineThickness="    0,150000"
[pcbnew/libraries]
LibDir=/usr/share/kicad/modules;../kicad_modules;../bigger_tracks_Three-phase_bridge_SMD;../open-coroco/src_DTC-SVM/kicad_modules
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_crystal&oscillator
LibName9=smd_dil
LibName10=smd_transistors
LibName11=libcms
LibName12=display
LibName13=led
LibName14=dip_sockets
LibName15=pga_sockets
LibName16=valves
LibName17=Three_phase_bridge
LibName18=SOD-123
LibName19=capacitors
LibName20=iut
LibName21=muonde
LibName22=powerint
LibName23=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/capacitors
LibName24=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/connect
LibName25=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/dip_sockets
LibName26=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/discret
LibName27=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/display
LibName28=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/divers
LibName29=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/iut
LibName30=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/led
LibName31=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/libcms
LibName32=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/muonde
LibName33=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/pga_sockets
LibName34=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/pin_array
LibName35=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/powerint
LibName36=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/smd_capacitors
LibName37=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/smd_dil
LibName38=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/smd_resistors
LibName39=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/smd_transistors
LibName40=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/sockets
LibName41=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/SOD-123
LibName42=/home/juan/open-coroco/src_DTC-SVM/kicad_modules/valves
LibName43=/home/juan/open-coroco/src_DTC-SVM/bigger_tracks_Three-phase_bridge_SMD/Three_phase_bridge
